#!/bin/sh
RAW=$(headsetcontrol -b)
#Found SteelSeries Arctis Nova 7!
#Battery: 100%
#Success!
NAME=$(echo $RAW | grep -o -P '(?<=Found).*(?=\! Battery)')
PERCENTAGE=$(echo $RAW | grep -oP 'Level: \K[0-9]+')
TEXT="$PERCENTAGE% 🎧"
STYLE="show"
if [ -z "$PERCENTAGE" ]; then
  PERCENTAGE=0
  NAME=""
  TEXT=""
  STYLE="hide"
fi
echo "{\"text\": \"$TEXT\", \"tooltip\": \"$NAME\", \"percentage\": $PERCENTAGE, \"class\": \"$STYLE\"}"