#!/bin/bash
playername=$(playerctl metadata --format '{{playerName}}')

player_icon=""
if [ "$playername" = "spotify" ]; then
    player_icon=""
    elif [ "$playername" = "youtube" ]; then
    player_icon=""
else
    player_icon="󰎆"
fi

song_title=$(playerctl metadata --format '{{title}}')
song_artist=$(playerctl metadata --format '{{artist}}')
song_info="$song_title $player_icon $song_artist"

echo {\"text\":\"$song_info\"}