#!/bin/sh
FILENAME=~/Videos/$(date +%s).mp4
pid=`pgrep wf-recorder`
status=$?
if [ $status != 0 ]; then
  wf-recorder -g "$(slurp)" -f $FILENAME
  # add to clipboard
  wl-copy < $FILENAME
else
  pkill --signal SIGINT wf-recorder
fi